### PR TITLE
Release Version of ASL GUI

### PR DESCRIPTION
**Pull request by 654wak654**
Version 1.0.0.0 is here. Ready to be shipped seperately or with ASL 1.2.0.

### CODE REVIEW

**Comment by Kugelschieber** [comment]
Hmm one thing I'm still missing is error handling. What do you do if ASL fails to compile a file?
I experienced this yesterday, I had an error in my code, but got no warning/error output. So I switched to the command line tool...

One way to implement this would be to check the result code and print the output of ASL if its not 0.
I work on better error ouput (not using "panic"), but currently this is really taking me away from using the GUI.

**Comment by 654wak654** [comment]
I have error checking but I guess I didn't make it really well. I was just getting the command line output and looked if it has "error" in it. If it did, I took the error message and showed the user an error dialog with it.

I can check if the exit code is 0 or not, and I can show something like "Unexpected error occurred." in the dialog.

**Comment by Kugelschieber** [comment]
Ah not needed if it's innow. Do you added this after 0.3.0?

**Comment by 654wak654** [comment]
I was checking for case-sensitive `Error` before, with this version I'm looking for not case-sensitive `error`. Will that do the trick?

This is where the fix happens:
https://github.com/654wak654/asl/commit/1c67be7d2e204342afad82096f0e0ab2d5ccbff6#diff-12499e24f22a01c1fda0367e2f06d562R291

**Comment by Kugelschieber** [comment]
Can you change that to "panic", ignoring the case?

**Comment by 654wak654** [comment]
[Done](https://github.com/654wak654/asl/commit/df79809cdde25065504c571cc50d1eeed4880222). Let me recompile a new exe too.

**Pull request merged**
